apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
spec:
  accessModes:
    - ReadWriteOnce # This means the volume can be mounted as read-write by a single node.
  resources:
    requests:
      storage: 25Gi # Request enough storage for the models (adjust as needed, e.g., 50Gi, 100Gi)