apiVersion: v1
kind: Service
metadata:
  name: ollama-service # Name used by llmchat-deployment to connect
  labels:
    app: ollama
spec:
  selector:
    app: ollama-pod # Selects pods with the label app: ollama-pod
  ports:
    - protocol: TCP
      port: 11435 # The port that other services will use to connect to this service
      targetPort: 11434 # Port the container is listening on
  type: ClusterIP # Only accessible within the cluster